/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahmaddzulfauzilazhim.pkg2210010389.tb;

/**
 *
 * @author  Ahmad Dzul Fauzil Azhim
 */
import com.toedter.calendar.JDateChooser;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
public class FramePengajuanCuti extends javax.swing.JFrame {

     private DefaultTableModel modelTabel;
    /**
     * Creates new form FramePengajuanCuti
     */
    public FramePengajuanCuti() {
        initComponents();
        this.setLocationRelativeTo(null);
    
          String[] kolom = {"ID", "Pegawai", "Tgl Pengajuan", "Tgl Mulai", "Tgl Selesai", "Jenis Cuti", "Status", "Catatan"};
        modelTabel = new DefaultTableModel(kolom, 0);
        TabelPengajuan.setModel(modelTabel);

  
        muatPegawai();

        muatData();

        TabelPengajuan.getSelectionModel().addListSelectionListener(e -> {
            int baris = TabelPengajuan.getSelectedRow();
            if (baris != -1) {
                txtidpengajuan.setText(modelTabel.getValueAt(baris, 0).toString());
                cmbpegawai.setSelectedItem(modelTabel.getValueAt(baris, 1).toString());
                try {
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    jdatepengajuan.setDate(sdf.parse(modelTabel.getValueAt(baris, 2).toString()));
                    jdatemulai.setDate(sdf.parse(modelTabel.getValueAt(baris, 3).toString()));
                    jdateselesai.setDate(sdf.parse(modelTabel.getValueAt(baris, 4).toString()));
                } catch (Exception ex) {}
                cmbjeniscuti.setSelectedItem(modelTabel.getValueAt(baris, 5).toString());
                cmbstatuspengajuan.setSelectedItem(modelTabel.getValueAt(baris, 6).toString());
                txtcatatan.setText(modelTabel.getValueAt(baris, 7).toString());
            }
        });
    }

    private void muatPegawai() {
        try (Connection kon = KoneksiDatabase.sambungkan();
             Statement st = kon.createStatement();
             ResultSet rs = st.executeQuery("SELECT nama_lengkap FROM pegawai")) {
            
            cmbpegawai.removeAllItems(); 
            while (rs.next()) {
                cmbpegawai.addItem(rs.getString("nama_lengkap"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal Muat Pegawai: " + ex.getMessage());
        }
    }

    private void muatData() {
        modelTabel.setRowCount(0); 
        try (Connection kon = KoneksiDatabase.sambungkan();
             Statement st = kon.createStatement();
             ResultSet rs = st.executeQuery("SELECT pc.*, p.nama_lengkap FROM pengajuan_cuti pc JOIN pegawai p ON pc.id_pegawai = p.id_pegawai")) {
            
            while (rs.next()) {
                Object[] data = {
                    rs.getInt("id_pengajuan"),
                    rs.getString("nama_lengkap"),
                    rs.getDate("tanggal_pengajuan"),
                    rs.getDate("tanggal_mulai_cuti"),
                    rs.getDate("tanggal_selesai_cuti"),
                    rs.getString("jenis_cuti"),
                    rs.getString("status_pengajuan"),
                    rs.getString("catatan")
                };
                modelTabel.addRow(data);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal Muat Data: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtidpengajuan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPengajuan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnubah = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        btnbersihkan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btncetak = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbpegawai = new javax.swing.JComboBox<>();
        jdatepengajuan = new com.toedter.calendar.JDateChooser();
        jdatemulai = new com.toedter.calendar.JDateChooser();
        jdateselesai = new com.toedter.calendar.JDateChooser();
        cmbjeniscuti = new javax.swing.JComboBox<>();
        cmbstatuspengajuan = new javax.swing.JComboBox<>();
        txtcatatan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Catatan:");

        TabelPengajuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelPengajuan);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID Pengajuan:");

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Pegawai:");

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tanggal Pengajuan:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal Mulai Cuti:");

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnbersihkan.setText("Bersihkan");
        btnbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihkanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tanggal Selesai Cuti:");

        btncetak.setText("Cetak CSV");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Cuti:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Status Pengajuan:");

        cmbjeniscuti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahunan", "Besar", "Melahirkan", "Alasan Penting" }));

        cmbstatuspengajuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diproses", "Disetujui", "Ditolak" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidpengajuan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbpegawai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdatepengajuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdatemulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdateselesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbjeniscuti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcatatan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbstatuspengajuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(txtidpengajuan))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(cmbpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jdatepengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jdatemulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jdateselesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbjeniscuti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbstatuspengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtcatatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnubah)
                    .addComponent(btnhapus)
                    .addComponent(btnbersihkan)
                    .addComponent(btncetak))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
         try (Connection kon = KoneksiDatabase.sambungkan()) {
            String sqlPegawai = "SELECT id_pegawai FROM pegawai WHERE nama_lengkap=?";
            PreparedStatement psPegawai = kon.prepareStatement(sqlPegawai);
            psPegawai.setString(1, cmbpegawai.getSelectedItem().toString());
            ResultSet rsPegawai = psPegawai.executeQuery();
            
            int idPegawai = 0;
            if (rsPegawai.next()) {
                idPegawai = rsPegawai.getInt("id_pegawai");
            }

            String sql = "INSERT INTO pengajuan_cuti (id_pegawai, tanggal_pengajuan, tanggal_mulai_cuti, tanggal_selesai_cuti, jenis_cuti, status_pengajuan, catatan) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = kon.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            ps.setInt(1, idPegawai);
            ps.setDate(2, new java.sql.Date(jdatepengajuan.getDate().getTime()));
            ps.setDate(3, new java.sql.Date(jdatemulai.getDate().getTime()));
            ps.setDate(4, new java.sql.Date(jdateselesai.getDate().getTime()));
            ps.setString(5, cmbjeniscuti.getSelectedItem().toString());
            ps.setString(6, cmbstatuspengajuan.getSelectedItem().toString());
            ps.setString(7, txtcatatan.getText());
            ps.executeUpdate();

            ResultSet rs = ps.getGeneratedKeys();
            if (rs.next()) {
                Object[] data = {
                    rs.getInt(1),
                    cmbpegawai.getSelectedItem(),
                    new java.sql.Date(jdatepengajuan.getDate().getTime()),
                    new java.sql.Date(jdatemulai.getDate().getTime()),
                    new java.sql.Date(jdateselesai.getDate().getTime()),
                    cmbjeniscuti.getSelectedItem(),
                    cmbstatuspengajuan.getSelectedItem(),
                    txtcatatan.getText()
                };
                modelTabel.addRow(data);
            }
            btnbersihkanActionPerformed(null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal Simpan: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
         try (Connection kon = KoneksiDatabase.sambungkan()) {
            String sqlPegawai = "SELECT id_pegawai FROM pegawai WHERE nama_lengkap=?";
            PreparedStatement psPegawai = kon.prepareStatement(sqlPegawai);
            psPegawai.setString(1, cmbpegawai.getSelectedItem().toString());
            ResultSet rsPegawai = psPegawai.executeQuery();
            
            int idPegawai = 0;
            if (rsPegawai.next()) {
                idPegawai = rsPegawai.getInt("id_pegawai");
            }

            String sql = "UPDATE pengajuan_cuti SET id_pegawai=?, tanggal_pengajuan=?, tanggal_mulai_cuti=?, tanggal_selesai_cuti=?, jenis_cuti=?, status_pengajuan=?, catatan=? WHERE id_pengajuan=?";
            PreparedStatement ps = kon.prepareStatement(sql);
            ps.setInt(1, idPegawai);
            ps.setDate(2, new java.sql.Date(jdatepengajuan.getDate().getTime()));
            ps.setDate(3, new java.sql.Date(jdatemulai.getDate().getTime()));
            ps.setDate(4, new java.sql.Date(jdateselesai.getDate().getTime()));
            ps.setString(5, cmbjeniscuti.getSelectedItem().toString());
            ps.setString(6, cmbstatuspengajuan.getSelectedItem().toString());
            ps.setString(7, txtcatatan.getText());
            ps.setInt(8, Integer.parseInt(txtidpengajuan.getText()));
            ps.executeUpdate();

            int baris = TabelPengajuan.getSelectedRow();
            modelTabel.setValueAt(cmbpegawai.getSelectedItem(), baris, 1);
            modelTabel.setValueAt(new java.sql.Date(jdatepengajuan.getDate().getTime()), baris, 2);
            modelTabel.setValueAt(new java.sql.Date(jdatemulai.getDate().getTime()), baris, 3);
            modelTabel.setValueAt(new java.sql.Date(jdateselesai.getDate().getTime()), baris, 4);
            modelTabel.setValueAt(cmbjeniscuti.getSelectedItem(), baris, 5);
            modelTabel.setValueAt(cmbstatuspengajuan.getSelectedItem(), baris, 6);
            modelTabel.setValueAt(txtcatatan.getText(), baris, 7);

             btnbersihkanActionPerformed(null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal Ubah: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try (Connection kon = KoneksiDatabase.sambungkan()) {
            String sql = "DELETE FROM pengajuan_cuti WHERE id_pengajuan=?";
            PreparedStatement ps = kon.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(txtidpengajuan.getText()));
            ps.executeUpdate();

            int baris = TabelPengajuan.getSelectedRow();
            modelTabel.removeRow(baris);
            btnbersihkanActionPerformed(null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal Hapus: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihkanActionPerformed
         txtidpengajuan.setText("");
        cmbpegawai.setSelectedIndex(0);
        jdatepengajuan.setDate(null);
        jdatemulai.setDate(null);
        jdateselesai.setDate(null);
        cmbjeniscuti.setSelectedIndex(0);
        cmbstatuspengajuan.setSelectedIndex(0);
        txtcatatan.setText("");
    }//GEN-LAST:event_btnbersihkanActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
         txtidpengajuan.setText("");
        cmbpegawai.setSelectedIndex(0);
        jdatepengajuan.setDate(null);
        jdatemulai.setDate(null);
        jdateselesai.setDate(null);
        cmbjeniscuti.setSelectedIndex(0);
        cmbstatuspengajuan.setSelectedIndex(0);
        txtcatatan.setText("");
    }//GEN-LAST:event_btncetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePengajuanCuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePengajuanCuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePengajuanCuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePengajuanCuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePengajuanCuti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPengajuan;
    private javax.swing.JButton btnbersihkan;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cmbjeniscuti;
    private javax.swing.JComboBox<String> cmbpegawai;
    private javax.swing.JComboBox<String> cmbstatuspengajuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdatemulai;
    private com.toedter.calendar.JDateChooser jdatepengajuan;
    private com.toedter.calendar.JDateChooser jdateselesai;
    private javax.swing.JTextField txtcatatan;
    private javax.swing.JTextField txtidpengajuan;
    // End of variables declaration//GEN-END:variables
}
